// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OuraDashboard.Data;

#nullable disable

namespace OuraDashboard.Data.Migrations
{
    [DbContext(typeof(OuraDbContext))]
    [Migration("20260418083430_AddSpo2ResilienceWorkout")]
    partial class AddSpo2ResilienceWorkout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveCalories")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("EquivalentWalkingDistance")
                        .HasColumnType("integer");

                    b.Property<int?>("HighActivityTime")
                        .HasColumnType("integer");

                    b.Property<int?>("InactiveTime")
                        .HasColumnType("integer");

                    b.Property<int?>("LowActivityTime")
                        .HasColumnType("integer");

                    b.Property<int?>("MediumActivityTime")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RestTime")
                        .HasColumnType("integer");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalCalories")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyActivities");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyHrv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AvgHrv5Min")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyHrvs");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyReadiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityBalanceContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyTemperatureContributor")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("HrvBalanceContributor")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PreviousDayActivityContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousNightContributor")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RecoveryIndexContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingHeartRateContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepBalanceContributor")
                        .HasColumnType("integer");

                    b.Property<double?>("TemperatureDeviation")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureTrendDeviation")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyReadinesses");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyResilience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<double?>("DaytimeRecovery")
                        .HasColumnType("double precision");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("SleepRecovery")
                        .HasColumnType("double precision");

                    b.Property<double?>("Stress")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyResilienceRecords");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySleep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("EfficiencyContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("LatencyContributor")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RemSleepContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("RestfulnessContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("TimingContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalSleepContributor")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailySleeps");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySpo2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreathingDisturbanceIndex")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("Spo2Average")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailySpo2s");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyStress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("DaytimeStress")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RecoveryHigh")
                        .HasColumnType("integer");

                    b.Property<int?>("StressHigh")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyStresses");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.HeartRateSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bpm")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp")
                        .IsUnique();

                    b.ToTable("HeartRateSamples");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.OuraUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.SleepSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageBreath")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("double precision");

                    b.Property<int?>("AverageHrv")
                        .HasColumnType("integer");

                    b.Property<int?>("AwakeTime")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BedtimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("BedtimeStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("Efficiency")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("HeartRateSeries")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("HrvSeries")
                        .HasColumnType("jsonb");

                    b.Property<int?>("Latency")
                        .HasColumnType("integer");

                    b.Property<int?>("LightSleepDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("LowestHeartRate")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RemSleepDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("RestlessPeriods")
                        .HasColumnType("integer");

                    b.Property<string>("SleepPhase30Sec")
                        .HasColumnType("text");

                    b.Property<string>("SleepPhase5Min")
                        .HasColumnType("text");

                    b.Property<int?>("TimeInBed")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalSleepDuration")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day");

                    b.HasIndex("UserId", "OuraId")
                        .IsUnique();

                    b.ToTable("SleepSessions");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Vo2Max", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double?>("Vo2MaxValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("Vo2Maxes");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Calories")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("EndDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Intensity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("StartDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day");

                    b.HasIndex("UserId", "OuraId")
                        .IsUnique();

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyActivity", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyHrv", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyHrvs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyReadiness", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyReadinesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyResilience", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyResilienceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySleep", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailySleeps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySpo2", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailySpo2s")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyStress", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyStresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.HeartRateSample", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("HeartRateSamples")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.SleepSession", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("SleepSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Vo2Max", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("Vo2Maxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Workout", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.OuraUser", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("DailyHrvs");

                    b.Navigation("DailyReadinesses");

                    b.Navigation("DailyResilienceRecords");

                    b.Navigation("DailySleeps");

                    b.Navigation("DailySpo2s");

                    b.Navigation("DailyStresses");

                    b.Navigation("HeartRateSamples");

                    b.Navigation("SleepSessions");

                    b.Navigation("Vo2Maxes");

                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
