// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OuraDashboard.Data;

#nullable disable

namespace OuraDashboard.Data.Migrations
{
    [DbContext(typeof(OuraDbContext))]
    partial class OuraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveCalories")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("EquivalentWalkingDistance")
                        .HasColumnType("integer");

                    b.Property<int?>("HighActivityTime")
                        .HasColumnType("integer");

                    b.Property<int?>("InactiveTime")
                        .HasColumnType("integer");

                    b.Property<int?>("LowActivityTime")
                        .HasColumnType("integer");

                    b.Property<int?>("MediumActivityTime")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RestTime")
                        .HasColumnType("integer");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalCalories")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyActivities");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyHrv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AvgHrv5Min")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyHrvs");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyReadiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityBalanceContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyTemperatureContributor")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("HrvBalanceContributor")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PreviousDayActivityContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousNightContributor")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RecoveryIndexContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingHeartRateContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepBalanceContributor")
                        .HasColumnType("integer");

                    b.Property<double?>("TemperatureDeviation")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureTrendDeviation")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyReadinesses");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyResilience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<double?>("DaytimeRecovery")
                        .HasColumnType("double precision");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("SleepRecovery")
                        .HasColumnType("double precision");

                    b.Property<double?>("Stress")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyResilienceRecords");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySleep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("EfficiencyContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("LatencyContributor")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RemSleepContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("RestfulnessContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("TimingContributor")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalSleepContributor")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailySleeps");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySpo2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreathingDisturbanceIndex")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("Spo2Average")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailySpo2s");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyStress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("DaytimeStress")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RecoveryHigh")
                        .HasColumnType("integer");

                    b.Property<int?>("StressHigh")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("DailyStresses");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.HeartRateSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bpm")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp")
                        .IsUnique();

                    b.ToTable("HeartRateSamples");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.OuraUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.SleepSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageBreath")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("double precision");

                    b.Property<int?>("AverageHrv")
                        .HasColumnType("integer");

                    b.Property<int?>("AwakeTime")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BedtimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("BedtimeStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("Efficiency")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("HeartRateSeries")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("HrvSeries")
                        .HasColumnType("jsonb");

                    b.Property<int?>("Latency")
                        .HasColumnType("integer");

                    b.Property<int?>("LightSleepDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("LowestHeartRate")
                        .HasColumnType("integer");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RemSleepDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("RestlessPeriods")
                        .HasColumnType("integer");

                    b.Property<string>("SleepPhase30Sec")
                        .HasColumnType("text");

                    b.Property<string>("SleepPhase5Min")
                        .HasColumnType("text");

                    b.Property<int?>("TimeInBed")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalSleepDuration")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day");

                    b.HasIndex("UserId", "OuraId")
                        .IsUnique();

                    b.ToTable("SleepSessions");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Vo2Max", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double?>("Vo2MaxValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("Vo2Maxes");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.WeatherHourlySample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ApparentTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double?>("CloudCoverPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("DewPointC")
                        .HasColumnType("double precision");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double?>("PrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("PressureMslHpa")
                        .HasColumnType("double precision");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("RainMm")
                        .HasColumnType("double precision");

                    b.Property<double?>("RelativeHumidityPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("ShortwaveRadiationWm2")
                        .HasColumnType("double precision");

                    b.Property<double?>("SnowDepthM")
                        .HasColumnType("double precision");

                    b.Property<double?>("SnowfallCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SoilMoisture0To7Cm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SoilTemperature0To7CmC")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<double?>("SunshineDurationSec")
                        .HasColumnType("double precision");

                    b.Property<double?>("SurfacePressureHpa")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeatherLocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("WeatherStationId")
                        .HasColumnType("integer");

                    b.Property<double?>("WindDirectionDeg")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindGustMs")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMs")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("WeatherLocationId", "TimestampUtc");

                    b.HasIndex("WeatherLocationId", "Source", "Model", "WeatherStationId", "TimestampUtc")
                        .IsUnique();

                    b.HasIndex("WeatherStationId");

                    b.ToTable("WeatherHourlySamples");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.WeatherLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<JsonDocument>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WeatherLocations");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.WeatherStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("ElementCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ElementName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("ObservationPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ObservationPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("WeatherLocationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeatherLocationId", "Source", "StationCode", "ElementCode")
                        .IsUnique();

                    b.ToTable("WeatherStations");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Calories")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("EndDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Intensity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OuraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("StartDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day");

                    b.HasIndex("UserId", "OuraId")
                        .IsUnique();

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.LlmInteraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("Day")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDay")
                        .HasColumnType("date");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RawRequestJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseText")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("StartDay")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserNameSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("InputHash", "Status");

                    b.HasIndex("Scope", "UserId", "Day", "CreatedAtUtc");

                    b.HasIndex("Scope", "UserId", "StartDay", "EndDay", "CreatedAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("LlmInteractions");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.LlmPrompt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Scope", "UserId", "IsActive");

                    b.HasIndex("Key", "Scope", "UserId", "Version")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("LlmPrompts");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyActivity", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyHrv", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyHrvs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyReadiness", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyReadinesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyResilience", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyResilienceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySleep", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailySleeps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailySpo2", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailySpo2s")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.DailyStress", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("DailyStresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.HeartRateSample", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("HeartRateSamples")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.SleepSession", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("SleepSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.LlmInteraction", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("LlmInteractions")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.LlmPrompt", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("LlmPrompts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Vo2Max", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("Vo2Maxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.WeatherHourlySample", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.WeatherLocation", "WeatherLocation")
                        .WithMany("HourlySamples")
                        .HasForeignKey("WeatherLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OuraDashboard.Data.Entities.WeatherStation", "WeatherStation")
                        .WithMany("HourlySamples")
                        .HasForeignKey("WeatherStationId");

                    b.Navigation("WeatherLocation");

                    b.Navigation("WeatherStation");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.WeatherStation", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.WeatherLocation", "WeatherLocation")
                        .WithMany("Stations")
                        .HasForeignKey("WeatherLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherLocation");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.Workout", b =>
                {
                    b.HasOne("OuraDashboard.Data.Entities.OuraUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.OuraUser", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("DailyHrvs");

                    b.Navigation("DailyReadinesses");

                    b.Navigation("DailyResilienceRecords");

                    b.Navigation("DailySleeps");

                    b.Navigation("DailySpo2s");

                    b.Navigation("DailyStresses");

                    b.Navigation("HeartRateSamples");

                    b.Navigation("LlmInteractions");

                    b.Navigation("LlmPrompts");

                    b.Navigation("SleepSessions");

                    b.Navigation("Vo2Maxes");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.WeatherLocation", b =>
                {
                    b.Navigation("HourlySamples");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("OuraDashboard.Data.Entities.WeatherStation", b =>
                {
                    b.Navigation("HourlySamples");
                });
#pragma warning restore 612, 618
        }
    }
}
