<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OuraDashboard.Sync\OuraDashboard.Sync.csproj" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
